[workspace]
members = ["rfb", "rfb-rig", "rfb-runtime", "ben"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
# Replace before publishing this workspace.
repository = "https://github.com/Cricle/rfb"


[profile.dev]
opt-level = 0

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
